"""
cascade.core.inference_process
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The InferenceProcess is Cascade's first-class runtime primitive.

Analogous to a Unix process — it carries identity, resource budgets,
runtime state, and full signal history from request birth to finish.
This is NOT a data transfer object. It is a live runtime entity that
the RuntimeController continuously reads and mutates during decoding.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


# ---------------------------------------------------------------------------
# State definition
# ---------------------------------------------------------------------------

class InferenceState(str, Enum):
    INITIALIZING   = "INITIALIZING"   # Budgets allocated, models loading
    LOCAL_FAST     = "LOCAL_FAST"     # Q2_K: cheap, exploratory, high throughput
    LOCAL_VERIFY   = "LOCAL_VERIFY"   # Q4_K_M: signal under watch, balanced
    LOCAL_RECOVER  = "LOCAL_RECOVER"  # Q8_0: maximum local precision
    REMOTE_ESCAPE  = "REMOTE_ESCAPE"  # Fireworks AI: parallel race or solo
    FINISHED       = "FINISHED"       # Winner selected, resources released


# Quality budget units consumed per state (not USD — intentionally abstract)
QUALITY_SPEND: dict[InferenceState, int] = {
    InferenceState.LOCAL_FAST:    20,
    InferenceState.LOCAL_VERIFY:  50,
    InferenceState.LOCAL_RECOVER: 80,
    InferenceState.REMOTE_ESCAPE: 200,
}


# ---------------------------------------------------------------------------
# Signal frame — snapshot of all runtime signals at one decoding step
# ---------------------------------------------------------------------------

@dataclass
class SignalFrame:
    """
    A single observation of all runtime signals captured at one decoding step.
    Appended to InferenceProcess.signal_history every N tokens.
    The EscalationPredictor uses a window of these to project the trajectory.
    """
    step:              int
    timestamp:         float
    token_entropy:     float   # Shannon entropy of next-token distribution [0, ∞]
    avg_logprob:       float   # Mean log-prob of recent tokens [-∞, 0]
    repetition_score:  float   # N-gram repetition rate [0, 1]
    generation_speed:  float   # Normalized tokens/sec [0, 1], inverted as signal
    fused_score:       float = 0.0   # Weighted combination — primary decision signal

    def to_dict(self) -> dict:
        return {
            "step":             self.step,
            "token_entropy":    round(self.token_entropy, 4),
            "avg_logprob":      round(self.avg_logprob, 4),
            "repetition_score": round(self.repetition_score, 4),
            "generation_speed": round(self.generation_speed, 4),
            "fused_score":      round(self.fused_score, 4),
        }


# ---------------------------------------------------------------------------
# InferenceProcess — the core primitive
# ---------------------------------------------------------------------------

@dataclass
class InferenceProcess:
    """
    First-class runtime object for a single inference request.

    Lifecycle:
        INITIALIZING → LOCAL_FAST → [LOCAL_VERIFY → LOCAL_RECOVER] → [REMOTE_ESCAPE] → FINISHED

    The RuntimeController reads and mutates this object throughout decoding.
    Think of it as the 'task_struct' of the Cascade inference OS.
    """

    # ── Request ──────────────────────────────────────────────────────────────
    prompt: str

    # ── Resource budgets (set at creation, enforced by state machine) ────────
    quality_budget:    int   = 100       # Abstract units; default allows up to Q8_0
    latency_budget_ms: int   = 5_000     # Hard wall-clock deadline
    cost_budget_usd:   float = 0.005     # Per-request API spend ceiling

    # ── Identity ─────────────────────────────────────────────────────────────
    process_id: str   = field(default_factory=lambda: str(uuid.uuid4())[:8])
    created_at: float = field(default_factory=time.monotonic)

    # ── Runtime state (mutated by RuntimeController) ─────────────────────────
    state:          InferenceState   = InferenceState.INITIALIZING
    signal_history: list[SignalFrame] = field(default_factory=list)

    # ── Execution accounting ─────────────────────────────────────────────────
    tokens_local:   int = 0   # Tokens generated on AMD GPU
    tokens_remote:  int = 0   # Tokens generated by Fireworks AI
    tokens_wasted:  int = 0   # Local tokens discarded on escalation
    tokens_reused:  int = 0   # Local draft tokens the remote leveraged

    # ── Outcome (populated when FINISHED) ────────────────────────────────────
    route_taken:      str            = "unknown"
    response:         Optional[str]  = None
    cost_actual_usd:  float          = 0.0
    quality_score:    float          = 0.0
    latency_ms:       float          = 0.0

    # ── Derived properties ────────────────────────────────────────────────────

    @property
    def waste_pct(self) -> float:
        """Fraction of local tokens that were ultimately discarded."""
        total_local = self.tokens_local
        return (self.tokens_wasted / total_local) if total_local > 0 else 0.0

    @property
    def elapsed_ms(self) -> float:
        return (time.monotonic() - self.created_at) * 1_000

    @property
    def budget_remaining(self) -> int:
        return max(0, self.quality_budget - QUALITY_SPEND.get(self.state, 0))

    @property
    def latest_signal(self) -> Optional[SignalFrame]:
        return self.signal_history[-1] if self.signal_history else None

    # ── Serialization ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "process_id":       self.process_id,
            "state":            self.state.value,
            "route_taken":      self.route_taken,
            "tokens_local":     self.tokens_local,
            "tokens_remote":    self.tokens_remote,
            "tokens_wasted":    self.tokens_wasted,
            "tokens_reused":    self.tokens_reused,
            "waste_pct":        round(self.waste_pct * 100, 1),
            "cost_usd":         round(self.cost_actual_usd, 6),
            "latency_ms":       round(self.latency_ms, 1),
            "quality_score":    round(self.quality_score, 3),
            "budget_remaining": self.budget_remaining,
            "signal_count":     len(self.signal_history),
            "latest_signal":    self.latest_signal.to_dict() if self.latest_signal else None,
        }
